name: C CI

# main(master) への push と PR 作成／更新時に走る
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Windows は MSYS2 で Bash が使えるようにセットアップ
    - name: Setup MSYS2 (Windows)
      if: runner.os == 'Windows'
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: make gcc

    - name: Build & Run Tests
      shell: bash
      run: cd testes && ../lua all.lua

